index.tsに打刻APIの追加
2023-ehime-u-pbl-ii-team-h/backend pull request #16
Opened 2023-12-14 01:12 UTC by i273tama

2023-12-14 01:26 UTC, MikuroXina requested changes

2023-12-14 01:26 UTC, MikuroXina commented on src/index.ts
> +  if ( !allowPattern.test(c.req.header("cf-connectiong-ip") as string) ) {
```suggestion
  if (!allowPattern.test(c.req.header("cf-connectiong-ip") ?? "")) {
```
存在しない場合に `null` になるわけですが, その場合は空文字列 `""` として扱うように null 結合演算子 `??` を使用するとよいでしょう.

2023-12-14 01:26 UTC, MikuroXina commented on src/index.ts
> +  .bind(session['id'])
```suggestion
  .bind(session.id)
```
これはこう書いても全く同じ意味になります. 他の箇所も同様にご対応お願いします.

2023-12-14 01:26 UTC, MikuroXina commented on src/index.ts
> +  if ( isExist ){
```suggestion
  const exists = existResult !== null;
  if (!exists){
```
変数名と意味が逆だと思います. また, こういう場合は三人称単数形を使ったほうがいいかもしれません

2023-12-14 01:26 UTC, MikuroXina commented on src/index.ts
> +  }
```suggestion
  const accountEntry = await c.env.DB
  .prepare("SELECT * FROM account WHERE role = 'STUDENT' AND id = ?")
  .bind(session.account_id)
  .first();
  const isStudent = accountEntry !== null;
  if (!isStudent) {
    return c.text("Unauthorized", 401);
  }
```
変数の意味が逆になっており, falsy も誤検知しかねないので `null` の取り扱いとして不適切です

2023-12-14 01:26 UTC, MikuroXina commented on src/index.ts
> +  .first();
ここまで多数のリクエストを行ってきましたが, すべてバラバラのリクエストなのでパフォーマンスやデータ整合性の観点から好ましくないです. [まとめてクエリ文を実行する機能](https://developers.cloudflare.com/d1/platform/client-api/#batch-statements) が用意されているのでそれを使いましょう.

2023-12-14 06:50 UTC, MikuroXina requested changes
全体的に SQL の記述がおかしいです. おそらくこのままだと動かないはずなので, 試しに実行して確かめてみてほしいです

2023-12-14 06:50 UTC, MikuroXina commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
```suggestion
  const [sessionEntry, accountEntry, attendanceBoardEntry] = await c.env.DB.batch([
```
`batch` 関数は結果のオブジェクトの配列を返すので, このように分割代入するのが正しいです. また, 変数名は camelCase の形式にしましょう.

2023-12-14 08:21 UTC, i273tama commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
実行するのはpnpm devを打った後のlocalhost:8787ですか？

2023-12-14 11:10 UTC, MikuroXina commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
はい, デバッグの起動はそれで大丈夫です. ただし Cookie による認証が動いているので, ブラウザのデベロッパーツールや HTTP サーバーをデバッグするツール等でうまく動作しているか監視しながらデバッグすることになると思います.
まだ何もデータが入っていないので, 以下のようなコマンドで SQL を実行してデータを追加することになるかもしれません. あとでテスト用のデータを注入する SQL スクリプトを用意してみることにします.
```sh
wrangler d1 execute attend-stamp --local --command 'INSERT INTO attendance_board (id, subject_id, start_from, seconds_from_start_to_be_late, seconds_from_be_late_to_end) VALUES ("1", "10", 1702552118984, 1800, 3600);'
```

2023-12-15 01:04 UTC, i273tama commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
SQL文の記述がおかしいというのは、文法的に間違っているという意味ですか？

2023-12-15 03:03 UTC, MikuroXina commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
クエリの際に予約語をダブルクォートでエスケープしてないことによるエラーと, スキーマの制約に違反するような変更によるエラーがいくつか発生することが考えられます.

2023-12-15 05:57 UTC, i273tama commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
了解です。ありがとうございます。

2023-12-17 05:17 UTC, i273tama commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
`"SELECT * FROM session WHERE id = ?"`
上記のように、prepare()の引数をダブルクォーテーションで囲んでいますが、これとはまた別にダブルクォートで囲むということですか？
また、スキーマの制約に違反するような変更によるエラーはどのように対処するのですか？

2023-12-17 05:25 UTC, MikuroXina commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
`batch` の戻り値の受け取り方について 118 ~ 121 行目に同じ問題があったのでまとめて書いてしまったのですが, そのクエリ文関する問題が起こりそうなのは 118 ~ 121 行目の `batch` の実行のほうになります. こちらでは `where` という属性に対する検索や変更が行われていますが SQL のキーワードである `WHERE` と被っているので, 識別子であることを示すためにダブルクォートで囲む必要があります.
スキーマの制約に違反するような変更によるエラーは 129 ~ 131 行目で既に対処されていますので問題ありません.

2023-12-17 06:06 UTC, i273tama commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
理解しました。ありがとうございます。

2023-12-17 06:26 UTC, MikuroXina commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
識別子はシングルクォートではなくダブルクォートで囲う必要があります. ダブルクォートで作る文字列の中でダブルクォートを書く場合は, `"....\"...."` のようにバックスラッシュでエスケープすることになります. 文字列をシングルクォートで作ったりバッククォート (こちらはテンプレートリテラル) にすることでも回避できますが, ここは間違って値が注入されることを避けたいのでエスケープする程度でよいでしょう.

2023-12-17 06:37 UTC, MikuroXina commented on src/index.ts
> +  const { existResult, accountEntry, attendance_boardResult } = await c.env.DB.batch([
121 行目の `INSERT` で使っている `where` という名前の属性も, 識別子になるようにダブルクォートで囲わないと動作しません.

2023-12-17 07:16 UTC, MikuroXina requested changes

2023-12-17 07:16 UTC, MikuroXina commented on src/index.ts
> +  }
```suggestion
  const honoSession = c.get("session");
  const session = honoSession.get("login") as Session | null;
  if ( !session ){
    return c.text("Unauthorized", 401);
  }
```
この `c.get("session")` で取得できるのは `hono-sessions` の API のオブジェクトですので, ここからさらに私たちが格納しているセッションのオブジェクトを取り出す必要があります. この `Session` 型は `./model/session` モジュールのものです.

2023-12-17 07:16 UTC, MikuroXina commented on src/index.ts
> +    c.env.DB.prepare("SELECT * FROM account WHERE role = 'STUDENT' AND id = ?").bind(session.account_id),
```suggestion
    c.env.DB.prepare("SELECT * FROM account WHERE role = 'STUDENT' AND id = ?").bind(session.account.id),
```
`account_id` という情報はなく, `account` プロパティの中にさらに `id` プロパティがあります. それを取得しましょう. 121 行目も同様に修正してください.

2023-12-17 07:16 UTC, MikuroXina commented on src/index.ts
> +  }
```suggestion
  const existsSession = existResult.results.length === 1;
  if (!existsSession) {
    return c.text("Unauthorized", 401);
  }
  //roleが学生か確認
  const isStudent = accountEntry.results.length === 1;
  if (!isStudent) {
    return c.text("Unauthorized", 401);
  }

  /*出席申請受付が開始されている科目をDBから探す、存在しなければ404を返す*/
  const isOpenBoard = attendanceBoardEntry.results.length === 1;
  if (!isOpenBoard) {
    return c.text("Not Found", 404);
  }
```
`batch` で返すオブジェクトは `D1Result` なのですが, その読み取り結果の列リストは `results` というプロパティで配列として返ってきます. この配列の長さを読んで判定すべきでしょう.

2023-12-17 07:16 UTC, MikuroXina commented on src/index.ts
> +    c.env.DB.prepare("INSERT INTO attendance (id, create_at, who, \"where\") VALUES (?1, ?2, ?3, ?4)").bind(nanoid(), new Date(), session.account_id, attendanceBoardEntry)
```suggestion
    c.env.DB.prepare("INSERT INTO attendance (id, create_at, who, \"where\") VALUES (?1, ?2, ?3, ?4)").bind(nanoid(), now, session.account_id, attendanceBoardEntry)
```
この上で取得している処理開始時点の現在時刻 `now` を使用しないと, データに矛盾が発生するおそれがあります.

2023-12-17 07:39 UTC, i273tama commented on src/index.ts
> +  }
90行目での処理について
/loginでセットしたセッションの情報を取得するから引数にloginを入れているのですか？

2023-12-17 07:46 UTC, MikuroXina commented on src/index.ts
> +  }
はい, そうです

2023-12-17 08:09 UTC, MikuroXina requested changes

2023-12-17 08:09 UTC, MikuroXina commented on src/index.ts
> +    c.env.DB.prepare("SELECT id FROM attendance_board WHERE start_from  <= ?1 AND seconds_from_be_late_to_end >= ?2").bind(now, now),
```suggestion
    c.env.DB.prepare("SELECT id FROM attendance_board WHERE start_from  <= ?1 AND seconds_from_be_late_to_end >= ?1").bind(now),
```
同じ値を当てはめるのであれば `?1` を 2 回使えばよいかと思います.

2023-12-17 08:09 UTC, MikuroXina commented on src/index.ts
> +  const existAttendance = attendResult != null;
```suggestion
  const existAttendance = attendResult.results.length !== 0;
```
こちらも `results` を読み取りましょう.

2023-12-17 08:09 UTC, MikuroXina commented on src/index.ts
> +  ])
これだと `attendResult` の検証より前に `INSERT` も実行されてしまうので `batch` でまとめて実行すべきではないかと思います. 素直に分けておいても問題ないでしょう.

2023-12-17 08:09 UTC, MikuroXina commented on src/index.ts
> +    c.env.DB.prepare("SELECT * FROM attendance WHERE \"where\" = ?").bind(attendanceBoardEntry),
```suggestion
    c.env.DB.prepare("SELECT * FROM attendance WHERE \"where\" = ?").bind(attendanceBoardEntry.results[0]),
```
`attendanceBoardEntry` そのものは読み取った値ではないです. その中の `results` の最初の要素を取り出して渡すことになると思います.

2023-12-17 08:34 UTC, MikuroXina requested changes

2023-12-17 08:34 UTC, MikuroXina commented on src/index.ts
> +  .bind(nanoid(), now, session.account.id, attendanceBoardEntry)
```suggestion
  .bind(nanoid(), now, session.account.id, attendanceBoardEntry.results[0])
```
こちらも `results` から取得する必要があると思います.

2023-12-17 08:34 UTC, MikuroXina commented on src/index.ts
> +  const request = c.env.DB.prepare("INSERT INTO attendance (id, create_at, who, \"where\") VALUES (?1, ?2, ?3, ?4)")
```suggestion
  const request = await c.env.DB.prepare("INSERT INTO attendance (id, create_at, who, \"where\") VALUES (?1, ?2, ?3, ?4)")
```
`Promise` の実行完了を `await` で待ちましょう.

2023-12-17 08:34 UTC, MikuroXina commented on src/index.ts
> +  }
```suggestion
  const attendEntry = await c.env.DB
    .prepare("SELECT * FROM attendance WHERE who = ? AND \"where\" = ?")
    .bind(session.account.id, attendanceBoardEntry.result[0])
    .first();
  if (attendEntry === null) {
    return c.text("Unprocessable Entity", 422);
  }
```
これ 1 回のクエリだけなら `first` でよさそうです. また, `who` による検索条件の指定もしないと正しく絞り込めないと思います.

2023-12-17 13:33 UTC, MikuroXina requested changes

2023-12-17 13:33 UTC, MikuroXina commented on src/index.ts
> +  const isOpenBoard = attendanceBoardEntry.result.length === 1;
```suggestion
  const isOpenBoard = attendanceBoardEntry.results.length === 1;
```
打ち間違えかと

2023-12-17 13:48 UTC, MikuroXina requested changes

2023-12-17 13:48 UTC, MikuroXina commented on src/index.ts
> +    c.env.DB.prepare("SELECT id FROM attendance_board WHERE start_from  <= ?1 AND seconds_from_be_late_to_end >= ?1").bind(now),
```suggestion
    c.env.DB.prepare(
        `
          SELECT id
          FROM attendance_board
          WHERE start_from <= ?1
            AND ?1 <= start_from + seconds_from_be_late_to_end
            AND id IN (
              SELECT subject_id
              FROM registration
              WHERE student_id = ?2
            )
        `,
      ).bind(Math.floor(now.getTime() / 1000), session.account.id),
```
こちらでも動かして試してみましたが,「その学生が受講している」条件の指定が抜けているので, このようなサブクエリを書く必要がありそうです.

2023-12-17 13:48 UTC, MikuroXina commented on src/index.ts
> +  const now = new Date();
```suggestion
  const now = Math.floor(Date.now() / 1000);
```
`Date` オブジェクトそのままを渡すとミリ秒になってしまってただの秒数にならないので, 秒数を取得しておく必要があります.

2023-12-18 01:51 UTC, MikuroXina requested changes

2023-12-18 01:51 UTC, MikuroXina commented on src/index.ts
> +          AND id IN (
```suggestion
          AND subject_id IN (
```
すいません, これは `subject_id` でした

2023-12-18 01:59 UTC, MikuroXina approved these changes

2023-12-18 01:59 UTC, merged

2023-12-18 02:08 UTC, i273tama commented on src/index.ts
> +  }
ありがとうございます。