Attendance board
2023-ehime-u-pbl-ii-team-h/backend pull request #19
Opened 2023-12-15 05:07 UTC by i475yama

条件文6つを持つdetermineStateの関数を作成

2023-12-15 06:08 UTC, MikuroXina requested changes

2023-12-15 06:08 UTC, MikuroXina commented on src/model/attendance-board.test.ts
> +const Latetime = new Date(toAttendAt.getTime() + board.secondsFromStartToBeLate * 1000 + board.secondsFromBeLateToEnd * 1000);//遅刻と認められる時間
```suggestion
const currentMs = Date.now();
const beLateMs = toAttendAt.getTime() + board.secondsFromStartToBeLate * 1000;
const endMs = toAttendAt.getTime() + board.secondsFromStartToBeLate * 1000 + board.secondsFromBeLateToEnd * 1000;
```
わざわざ `Date` に変換せずとも, 最初からすべてミリ秒にして判定したほうが楽かと思います

2023-12-15 06:08 UTC, MikuroXina commented on src/model/attendance-board.test.ts
> +function determineState(board: AttendanceBoard, toAttendAt: Date): AttendanceState {
```suggestion
export type AttendanceBoard = {
    readonly id: ID<AttendanceBoard>;
    readonly subject: ID<Subject>;
    readonly startFrom: Date;
    readonly secondsFromStartToBeLate: number;
    readonly secondsFromBeLateToEnd: number;
};

export type AttendanceState = 
    | "TOO_EARLY"
    | "ATTENDED"
    | "BE_LATE"
    | "CLOSED"
;

export function determineState(board: AttendanceBoard, toAttendAt: Date): AttendanceState {
```
作ったものを export しましょう

2023-12-15 06:08 UTC, MikuroXina commented on src/model/attendance-board.test.ts
> +
```suggestion
import { Subject } from "./subject";

```
`Subject` の import が抜けています

2023-12-15 12:23 UTC, MikuroXina requested changes

2023-12-15 12:23 UTC, MikuroXina commented on src/model/attendance-board.test.ts
> +}
```suggestion
}
if (currentMs < beLateMs){
    return "ATTENDED";
}
if (currentMs < endMs){
    return "BE_LATE";
}
return "CLOSED";
```
すべての分岐が `return` で終わるので, `else` は不要です. また, 2 つに分かれている条件をまとめることができます.

2023-12-15 14:09 UTC, MikuroXina requested changes

2023-12-15 14:09 UTC, MikuroXina commented on src/model/attendance-board.test.ts
> +}
```suggestion
    return "CLOSED";
```
これだと `endMs` と `currentMs` が同じ場合の条件が抜けています. そもそもここに到達した時点で残る選択肢は `"CLOSED"` しかないので, `if` は不要です.

2023-12-15 14:51 UTC, MikuroXina approved these changes

2023-12-15 14:52 UTC, MikuroXina requested changes

2023-12-15 14:52 UTC, MikuroXina commented on src/model/attendance-board.test.ts
今気づきました. ファイル名がおかしいです. `.test.ts` は自動テストを書くためのファイルの拡張子ですので, こういった実装を書くファイル名には適しません. `.test` の部分を取り除いておきましょう.

2023-12-16 02:19 UTC, MikuroXina requested changes

2023-12-16 02:19 UTC, MikuroXina commented on src/model/attendance-board.test.ts
たしかに `attendance-board.ts` は追加されましたが, `.test.ts` のほうが残ったままです. ファイルの削除もステージしてコミットできます. もしどうすればいいのか分からないのであれば, 以下のコマンドをお試しください.
```sh
git rm src/model/attendance-board.test.ts
```

2023-12-16 23:25 UTC, i475yama commented
ありがとうございます。
申し訳ないのですが、本日予定があって夜まで帰ることができないので修正するのが遅くなります。
本日中には行う予定です

2023-12-18 01:34 UTC, MikuroXina approved these changes

2023-12-18 01:36 UTC, merged