出席状況取得APIの追加
2023-ehime-u-pbl-ii-team-h/backend pull request #21
Opened 2023-12-18 14:41 UTC by i273tama

2023-12-18 14:57 UTC, MikuroXina requested changes

2023-12-18 14:57 UTC, MikuroXina commented on src/index.ts
> +app.get("/attendance/:course_id", async(c) => {
```suggestion
app.get("/attendances/:course_id", async (c) => {
```
ここは複数形です.

2023-12-18 14:57 UTC, MikuroXina commented on src/index.ts
> +  }
すべてのデータを取り出して数えるのは効率が悪いです. SQL の `COUNT` 集計関数などを使用して SQL 側で数えましょう

2023-12-18 14:57 UTC, MikuroXina commented on src/index.ts
> +  .all();
```suggestion
```
SQL の集計関数を使うようにすればこちらは不要になると思います.

2023-12-18 23:38 UTC, i273tama commented on src/index.ts
> +  }
ATTENDEDなどのstateはDBのどのテーブルに保存されますか？

2023-12-19 00:58 UTC, MikuroXina commented on src/index.ts
> +  }
それらは記録された時刻から判定した結果の名称なので, テーブルに保存されていません. ある出席申請受付ごとに, その出席時刻が特定の範囲に収まっているかの条件でフィルタしたものを数えることになります. 少し複雑な SQL にはなりますので, 分からなければぜひまたお聞きください.

2023-12-19 05:02 UTC, i273tama commented
今回修正したSQL文のテスト方法について変数のときはどのようにテストすればいいのか教えてほしいです。

2023-12-19 08:32 UTC, MikuroXina commented
@i273tama 変数というのがバインディングのことでしたら, 今のところはいくつか値を入れた SQL 文を実行してみて動作テストできれば大丈夫だと思います. 例えば今の SQL 文ですとこのようにテストすればよいかと思います.
```sh
pnpm wrangler d1 execute attend-stamp --local --comand='
    SELECT SUM(
        CASE WHEN
            attendance.create_at BETWEEN attendance_board.start_from AND attendance_board.seconds_from_start_to_be_late
        THEN 1
        ELSE 0
        END
    ) AS on_time
    FROM attendance
    NATURAL JOIN attendance_board
    WHERE attendance.who = \'acc01\' AND attendance_board.subject_id = \'sub01\''
````

2023-12-19 08:38 UTC, MikuroXina requested changes

2023-12-19 08:38 UTC, MikuroXina commented on src/index.ts
> +      SUM(CASE WHEN attendance.create_at >= attendance_board.seconds_from_to_be_late_to_end THEN 1 ELSE 0 END) AS miss
`create_at` ではなく, 過去分詞形の `created_at` です.
また, `start_from` と一緒に `seconds_from_start_to_be_late` や `from_to_be_late_to_end` を比較しても, 単位系が違う (時刻と秒数になっている) ので動作しないはずです. 例えば遅刻扱いになる時刻は `created_at + seconds_from_start_to_be_late` のように書く必要があります.

2023-12-19 08:38 UTC, MikuroXina commented on src/index.ts
> +    NATURAL JOIN attendance_board
同じタイプの値が入っているカラムがそれぞれのテーブルで違う名前なので, 自然結合ではなく他の結合を用いて, 結合の条件を書かないと動作しないでしょう.

2023-12-19 08:38 UTC, MikuroXina commented on src/index.ts
> +  });
```suggestion
  const { on_time, late, miss } = c.env.DB
  .prepare(`
    SELECT
      SUM(CASE WHEN attendance.create_at BETWEEN attendance_board.start_from AND attendance_board.seconds_from_start_to_be_late THEN 1 ELSE 0 END) AS on_time,
      SUN(CASE WHEN attendance.create_at BETWEEN attendance_board.seconds_from_start_to_be_late AND attendance_board.from_to_be_late_to_end THEN 1 ELSE 0 END) AS late,
      SUM(CASE WHEN attendance.create_at >= attendance_board.seconds_from_to_be_late_to_end THEN 1 ELSE 0 END) AS miss
    FROM attendance
    NATURAL JOIN attendance_board
    WHERE attendance.who = ?1 AND attendance_board.subject_id = ?2
  `)
  .bind(session.account.id, subjectID)
  .first();

  /*JSON形式で返す*/
  return c.json({
    on_time,
    late,
    miss,
  });
```
分割代入しておけばシンプルに書けます.

2023-12-19 22:47 UTC, i273tama commented
ありがとうございます。

2023-12-19 23:42 UTC, i273tama commented
ターミナルで以下のようにテストを実行しようとしたところ、Error: must provide --command or --file. というエラーが出てしまいます。解決策はありますか？
```
pnpm wrangler d1 execute attend-stamp --local --command='
  SELECT
    SUM(CASE WHEN attendance.created_at BETWEEN attendance_board.start_from AND (atendance.created_at + attendance_board.seconds_from_start_to_be_late) THEN 1 ELSE 0 END) AS on_time
    FROM attendance
    INNER JOIN attendance_board
      ON attendance.\'where\' = attendance.board.id
    WHERE attendance.who = \'acc01\' AND attendance_board.subject_id = \'sub01\';'
```

2023-12-20 04:40 UTC, MikuroXina commented
@i273tama こちらで色々試したところ, エスケープのしかたを間違えていたようなので以下のようにしたら実行はできました. ただ私が使用しているシェルは zsh なので, お使いのシェルにあわせて, [Powershell の場合のクォート (`"` や `'`) の書き方](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules) のように記述を変えないと動かないかもしれないです.
```sh
pnpm wrangler d1 execute attend-stamp --local --command=$'
  SELECT
    SUM(CASE WHEN attendance.created_at BETWEEN attendance_board.start_from AND (attendance.created_at + attendance_board.seconds_from_start_to_be_late) THEN 1 ELSE 0 END) AS on_time
    FROM attendance
    INNER JOIN attendance_board
      ON attendance.\'where\' = attendance_board.id
    WHERE attendance.who = \"acc01\" AND attendance_board.subject_id = \"sub01\";'
```

2023-12-20 06:02 UTC, i273tama commented
いろいろ`"`と`'`を入れ替えて試しましたがうまくいかなかったので、テスト用のsqlファイルを作成し、その中にテストしたいSQL文を入れて--fileで実行したら実行できました。
お手数をおかけいたしました。

2023-12-20 06:19 UTC, MikuroXina requested changes

2023-12-20 06:19 UTC, MikuroXina commented on src/index.ts
> +      ON attendance.\"where\" = attendance.board.id
```suggestion
      ON attendance."where" = attendance_board.id
```
これはバッククォート `` ` `` で囲ったテンプレートリテラルの中なので, `"` はエスケープせずに書けると思います. またカラムは `attendance_board` の `id` だと思います.

2023-12-20 06:19 UTC, MikuroXina commented on src/index.ts
> +    miss: miss
```suggestion
    on_time: on_time ?? 0,
    late: late ?? 0,
    miss: miss ?? 0,
```
該当するカラムがない場合に `null` を返すようなので, [null 合体演算子 `??`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) で `0` へフォールバックさせておきたいです.

2023-12-20 06:48 UTC, MikuroXina requested changes

2023-12-20 06:48 UTC, MikuroXina commented on src/index.ts
> +  const [subjectResult, registration] = c.env.DB.batch([
```suggestion
  const [subjectResult, registration] = await c.env.DB.batch([
```
`Promise` が `await` されていないので分割代入で取り出せません.

2023-12-20 06:48 UTC, MikuroXina commented on src/index.ts
> +  const { on_time, late, miss } = c.env.DB
```suggestion
  const entry = await c.env.DB
```
`Promise` が `await` されていないので分割代入で取り出せません.
また, クエリが不正だった場合にそのエラーを特定するのが難しくなるので, `entry` などの変数に一旦受け取っておいてから, 以下のように問題無いか検査して取り出すコードを書いたほうがよさそうです.
```ts
  if (entry === null) {
    throw new Error("SUM up query was invalid");
  }
  const { on_time, late, miss } = entry;
```

2023-12-20 23:59 UTC, MikuroXina requested changes

2023-12-20 23:59 UTC, MikuroXina commented on src/index.ts
> +      SUM(CASE WHEN attendance.created_at BETWEEN attendance_board.start_from AND (atendance.created_at + attendance_board.seconds_from_start_to_be_late) THEN 1 ELSE 0 END) AS on_time,
```suggestion
      SUM(CASE WHEN attendance.created_at BETWEEN attendance_board.start_from AND (attendance.created_at + attendance_board.seconds_from_start_to_be_late) THEN 1 ELSE 0 END) AS on_time,
```
typo と思われます

2023-12-20 23:59 UTC, MikuroXina commented on src/index.ts
> +    c.env.DB.prepare("SELECT id FROM subjet WHERE id = ?").bind(subjectID),
```suggestion
    c.env.DB.prepare("SELECT id FROM subject WHERE id = ?").bind(subjectID),
```
typo と思われます

2023-12-21 00:24 UTC, MikuroXina requested changes

2023-12-21 00:24 UTC, MikuroXina commented on src/index.ts
> +      SUM(CASE WHEN attendance.created_at BETWEEN (attendance_board.start_from + attendance_board.seconds_from_start_to_be_late) AND (attendance_board.start_from + attendance_board.seconds_from_start
この 2 つの SUM ですが, 条件が半開区間になっていないのでギリギリの時間のものが二重に集計されそうです. `BETWEEN ~ AND ~` の後ろ側の範囲を `- 1` するか, 2 つの比較を `AND` でつなげて書いたほうがよさそうです.

2023-12-21 00:35 UTC, MikuroXina approved these changes

2023-12-21 00:42 UTC, merged