科目情報取得APIの追加
2023-ehime-u-pbl-ii-team-h/backend pull request #28
Opened 2023-12-21 14:07 UTC by i273tama

2023-12-21 14:17 UTC, MikuroXina requested changes

2023-12-21 14:17 UTC, MikuroXina commented on src/index.ts
> +  const { attendanceBoardID, startFrom, secondsFromStartToBeLate, secondsFromBeLateToEnd } = attendanceBoardEntry;
```suggestion
  if (!subjectEntry.success) {
    throw new Error("Subject query was invalid");
  }
  if (!teacherEntry.success) {
    throw new Error("Charge query was invalid"); 
  }
  if (!attendanceBoardEntry.success){
    return c.text("Not Found", 404);
  }

  const { subjectName } = subjectEntry.results[0];
  const { chargeTeacherID } = teacherEntry;.results[0]
  const { attendanceBoardID, startFrom, secondsFromStartToBeLate, secondsFromBeLateToEnd } = attendanceBoardEntry.results[0];
```
[`batch` 関数などは `D1Result` オブジェクトを返す](https://developers.cloudflare.com/d1/platform/client-api/#return-object) ようになっています. このデータは, `success` フィールドで成功したかをチェックし, チェック後に `results` フィールドから取得できたカラムの配列を読み取るように書く必要があります.

2023-12-21 14:17 UTC, MikuroXina commented on src/index.ts
> +      startFrom: startFrom.toISOString(),
```suggestion
      startFrom: new Date(startFrom * 1000).toISOString(),
```
`startFrom` は UNIX エポックの秒数の数値型ですので, `toISOString` というメソッドはありません. `Date.prototype.toISOString()` を使いたいのであれば `Date` オブジェクトに変換しましょう.

2023-12-22 05:00 UTC, MikuroXina requested changes

2023-12-22 05:00 UTC, MikuroXina commented on src/index.ts
> +  const { attendanceBoardID, startFrom, secondsFromStartToBeLate, secondsFromBeLateToEnd } = attendanceBoardEntry.results[0];
```suggestion
  const { name: subjectName } = subjectEntry.results[0];
  const { teacher_id: chargeTeacherID } = teacherEntry.results[0];
  const { id: attendanceBoardID, start_from: startFrom, seconds_from_start_to_be_late: secondsFromStartToBeLate, seconds_from_be_late_to_end: secondsFromBeLateToEnd } = attendanceBoardEntry.results[0];
```
これは SQL で `SELECT` したカラム名のキーバリューになりますから, それに合わせて分割代入する必要があると思います.

2023-12-22 12:26 UTC, i273tama commented on src/index.ts
> +  const { attendanceBoardID, startFrom, secondsFromStartToBeLate, secondsFromBeLateToEnd } = attendanceBoardEntry.results[0];
例えば192行目では、nameのキーで取り出した値をsubjectNameに代入しているという認識でいいですか？

2023-12-22 12:55 UTC, MikuroXina approved these changes

2023-12-22 12:57 UTC, merged