Tamai mana/eph 73
2023-ehime-u-pbl-ii-team-h/backend pull request #39
Opened 2024-01-12 02:37 UTC by i273tama

2024-01-12 02:58 UTC, MikuroXina requested changes

2024-01-12 02:58 UTC, MikuroXina commented on src/index.ts
> +  }
`Error` を `throw` すると 500 Internal Server Error となってしまいます. これらの条件はユーザのリクエストの認証情報が不正だった場合に引っかかるので, 401 Unauthroized を返すべきです.

2024-01-12 02:58 UTC, MikuroXina commented on src/index.ts
> +    const msUntil = Date.parse(until);
`Date.parse` を使う場合は, 不正な文字列をパースした場合には `NaN` が返ってきますのでそのチェックが必要です. また, データベース上の値はミリ秒ではなく秒数なので, `Math.floor(... / 1000)` のような処理で秒数に変換する必要もあるでしょう.

2024-01-12 02:58 UTC, MikuroXina commented on src/index.ts
> +    .prepare("SELECT id, created_at , who FROM attendance WHERE created_at BETWEEN ?1 AND ?2")
`attendance."where"` に関する絞り込みを行っていないので, 関係ないデータも取り出しています. ``attendance."where"` がパラメータの `board_id` に等しいかどうかの条件も加えましょう.

2024-01-12 02:58 UTC, MikuroXina commented on src/index.ts
> +    .raw();
オブジェクトのデータをすべて取得したいのであれば, [`all` メソッド](https://developers.cloudflare.com/d1/reference/client-api/#await-stmtall) を使うべきです.

2024-01-12 02:58 UTC, MikuroXina commented on src/index.ts
> +    })
```suggestion
    return c.json({
      id: attendanceId,
      created_at: createdAt,
      who: {
        id: login.account.id,
        name: login.account.name,
        email: login.account.email,
      },
    })
```
セッションの情報が正当である (予測不可能な ID をクライアントが知っていた) と確認したので, そのセッションに入っているアカウント情報を使えばクエリは不要です.

2024-01-12 02:58 UTC, MikuroXina commented on src/index.ts
> +  if ( since !== null && until !== null ){ //since, untilがどちらも存在
パラメータが存在するかどうかのパターンで分岐しているようですが, 指定されなかったほうを十分に小さい/大きい値にフォールバックさせれば 1 つのコードで実装できると思います.

2024-01-12 02:58 UTC, MikuroXina commented on src/index.ts
> +  const accountInfo = await accountRepo.getStudentOrTeacher(login.account.id);
main ブランチの最新のコードで, ミドルウェアの処理としてレポジトリに問い合わせてセッション情報が有効かどうかを確認しています. そのセッション情報にアカウントの情報が入っていますので, DB に問い合わせなくても `login.account` でそのまま利用できます.

2024-01-12 11:07 UTC, MikuroXina requested changes

2024-01-12 11:07 UTC, MikuroXina commented on src/index.ts
> +  return { secondsSince: secondsSince, secondsUntil: secondsUntil }
```suggestion
  return { secondsSince, secondsUntil };
```
格納するキーと変数名が同じなら略記できます.

2024-01-12 11:07 UTC, MikuroXina commented on src/index.ts
> +  });
```suggestion
  const { results } = attendanceEntry;
  if (results === null) {
    throw new Error("attendance query was invalid");
  }

  return c.json(results.map(({ id, created_at }) => ({
      id,
      created_at,
      who: {
        // ...
      },
  }));
```
`attendanceEntry` にはクエリの実行結果を表すオブジェクトが入っており, `attendanceEntry.results` はこの `SELECT` した結果である `{ id: ID<Attendance>, created_at: number }` のリスト (つまり `{ id: ID<Attendance>, created_at: number }[]`) が格納されています.
Issue では, このリスト内の 1 つ 1 つの全ての要素を加工して所望のレスポンスの形式に加工する指示をしています. したがって, 上記のようなコードを書くことになるはずです.
また, なぜか `who` にログインの情報を入れていますが, これは「出席申請の項目ごとに, その出席申請をした学生の情報」を入れるものです. このコードではまだ情報が足りていないので, SQL のクエリの文を `account` との `JOIN` を行うように書き換える必要があるでしょう.

2024-01-15 05:16 UTC, MikuroXina commented on src/index.ts
> +  const accountInfo = await accountRepo.getStudentOrTeacher(login.account.id);
この問題がまだ修正されていません

2024-01-15 06:57 UTC, i273tama commented on src/index.ts
> +  const accountInfo = await accountRepo.getStudentOrTeacher(login.account.id);
すみません、抜けていました。
login.account.roleでroleを利用できるということですか？

2024-01-15 06:59 UTC, MikuroXina commented on src/index.ts
> +  const accountInfo = await accountRepo.getStudentOrTeacher(login.account.id);
はい, そうなります

2024-01-15 07:48 UTC, i273tama commented on src/index.ts
> +  const accountInfo = await accountRepo.getStudentOrTeacher(login.account.id);
お答えいただきありがとうございます。

2024-01-15 09:17 UTC, MikuroXina requested changes

2024-01-15 09:17 UTC, MikuroXina commented on src/index.ts
> +app.get("/subject/:subject_id/:board_id/attendances", async (c) => {
```suggestion
app.get("/subjects/:subject_id/:board_id/attendances", async (c) => {
```
ここは複数形でお願いします.

2024-01-15 09:17 UTC, MikuroXina commented on src/index.ts
> +  const login = HonoSession.get("login") as Session | null;
```suggestion
  const login = c.get("login");
```
現行の main ブランチのコードはこれだけでログイン情報を取得できるようになっているので, このようにお願いします.

2024-01-16 00:23 UTC, MikuroXina approved these changes

2024-01-16 00:26 UTC, merged