「エラー」に記された適切な HTTP エラーレスポンスを返す記述を追加する.
2023-ehime-u-pbl-ii-team-h/backend pull request #42
Opened 2024-01-15 01:26 UTC by i475yama

2024-01-17 05:09 UTC, MikuroXina requested changes

2024-01-17 05:09 UTC, MikuroXina commented on src/index.ts
> +import { boolean, z } from "zod";
```suggestion
```
VS Code などのエディタは, プログラムを入力する際に, 補完に出てきた名前を選択すると自動で `import` する機能があります. この 2 行はその影響で間違えて追加されたままになったのだと思いますが, 不要なので除去してほしいです.

2024-01-17 05:09 UTC, MikuroXina commented on src/index.ts
> +  rows.every((row) => row.success);
```suggestion
```
この行は実行結果を使わずに捨てているので, 実行処理としての意味が無く不要です.

2024-01-18 04:38 UTC, MikuroXina commented on src/index.ts
> +import { boolean, z } from "zod";
@i475yama すいません, Suggest で消しすぎました. Zod の `z` は使っていたので `import { z } from "zod";` は残しておく必要があります.

2024-01-18 09:49 UTC, MikuroXina commented on src/index.ts
> +import { boolean, z } from "zod";
小さい変更なのでもうこちらでやっておきますね.

2024-01-18 09:50 UTC, MikuroXina approved these changes

2024-01-18 09:51 UTC, merged

2024-01-18 12:35 UTC, i475yama commented on src/index.ts
> +import { boolean, z } from "zod";
ありがとうございます。よろしくお願いします